//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientInfo
    {
        public int PatientInfoID { get; set; }
        public string PatientNameGroup1 { get; set; }
        public string PatientNameGroup2 { get; set; }
        public string PatientNameGroup3 { get; set; }
        public string PatientID { get; set; }
        public Nullable<System.DateTime> PatientBirthDate { get; set; }
        public string PatientSex { get; set; }
        public string EthnicGroup { get; set; }
        public string PatientComment { get; set; }
        public byte[] PatientInfoTS { get; set; }
        public string PatientFileInfo { get; set; }
        public string PatientDisease { get; set; }
    }
}
